import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,CalendarDays,Coffee,MapPin,Users} from 'lucide-react';
import {CommunityBoard} from '@/components/CommunityBoard';

const ticketUrl='https://square.link/u/1eDmFUid';

export default function Community(){return <>
  <section className="bg-fundy text-white"><div className="container-x grid min-h-[600px] items-center gap-12 py-16 lg:grid-cols-[1.1fr_.9fr]"><div><span className="pill border-white/20 bg-white/10 text-sand">The community layer</span><h1 className="display mt-6 text-6xl leading-[.9] sm:text-7xl">Outside is better<br/><span className="text-sand">together.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">No feeds. No follower counts. Just local people looking for good company, good trails and a reason to get out the door.</p><Link href="#board" className="btn-secondary mt-8">See the adventure board <ArrowRight size={16}/></Link></div><div className="relative min-h-[430px] overflow-hidden rounded-[2.5rem] border border-sand/30 bg-white/5"><Image src="/images/nathan-dumlao-ozVQrfENFOs-unsplash.jpg" alt="Hush Hush coffee event at Nomad's Cafe" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover object-top"/><div className="absolute inset-0 bg-gradient-to-t from-forest/85 via-forest/10 to-transparent"/><div className="absolute bottom-6 left-6 right-6 grid gap-3 sm:grid-cols-2"><Mini icon={Coffee} title="Nomad's Cafe" text="Secret adventure + pop-up coffee"/><Mini icon={Users} title="Find your people" text="Post a plan. Join a plan."/><Mini icon={CalendarDays} title="Local events" text="Clinics, swaps & trail days"/><Mini icon={MapPin} title="Trail reports" text="Real local knowledge"/></div></div></div></section>
  <section className="container-x py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="pill">Coming up</span><h2 className="display mt-4 text-5xl text-forest">Nomad's Cafe.</h2><p className="mt-3 max-w-2xl text-forest/60">A little secret. A sweet adventure. Coffee somewhere unexpected. New friends & Deeper Connections.</p></div><Link href="/events" className="btn-ghost">See all events <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Event image="/images/nathan-dumlao-ozVQrfENFOs-unsplash.jpg" alt="Hush Hush coffee event at Nomad's Cafe" title="Nomad's Cafe" date="Saturday · 7–10 AM" spots="36 / 40 spots" text="The Drop happens at a secret trailhead. Coordinates released 24 hours out. No earlier. No route names, no trailhead teased in advance — just a pin and a time"/><Event image="/assets/photography/fundy-paddle.jpg" alt="Kayak on the Bay of Fundy" title="Full moon paddle" date="Thursday · 7–9 PM" spots="12 / 14 spots" text="Calm water, headlamps and hot chocolate."/><Event image="/assets/photography/fundy-forest.jpg" alt="Forest trail in Atlantic Canada" title="Trail Steward Saturday" date="Sept 12 · 9 AM" spots="Open to all" text="Help care for a local trail, then share lunch."/></div></section>
  <section id="board" className="bg-sand/35 py-20"><div className="container-x"><div className="max-w-2xl"><span className="pill">Adventure board</span><h2 className="display mt-5 text-5xl text-forest">Someone out there is looking for the same adventure.</h2><p className="mt-4 text-forest/60">Share what you're planning or jump into someone else's plan. Keep it local. Keep it human.</p></div><div className="mt-10"><CommunityBoard/></div></div></section>
</>}

function Mini({icon:Icon,title,text}:{icon:any,title:string,text:string}){return <div className="rounded-3xl bg-white/10 p-5"><Icon className="text-sand" size={21}/><h3 className="mt-6 font-black">{title}</h3><p className="mt-1 text-sm text-white/60">{text}</p></div>}
function Event({image,alt,title,date,spots,text}:{image:string,alt:string,title:string,date:string,spots:string,text:string}){return <article className="overflow-hidden rounded-3xl bg-white shadow-soft"><div className="relative aspect-[16/9]"><Image src={image} alt={alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-forest/70 to-transparent"/><span className="absolute left-5 top-5 pill border-white/20 bg-white/90">Hush Hush</span></div><div className="p-6"><div className="flex items-center justify-between"><span className="text-xs font-bold text-rust">{spots}</span></div><h3 className="display mt-6 text-3xl text-forest">{title}</h3><div className="mt-2 text-xs font-black uppercase tracking-[.14em] text-forest/45">{date}</div><p className="mt-4 text-sm leading-6 text-forest/60">{text}</p><a href={ticketUrl} className="btn-primary mt-6 w-full">Buy Tickets</a></div></article>}
