import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,Clock,Radio,ShoppingBag} from 'lucide-react';
import {ProductCard,Product} from '@/components/ProductCard';

const drop:Product[]=[
 {name:'Trail Pack 55',brand:'Osprey',price:'$165',condition:'Excellent',category:'Packs',location:'Moncton',image:'/assets/photography/fundy-hiker.jpg',alt:'Hiker wearing a technical backpack'},
 {name:'Hubba Hubba 2',brand:'MSR',price:'$310',condition:'Like new',category:'Camping',location:'Moncton',image:'/assets/photography/fundy-forest.jpg',alt:'Forest trail beside lush greenery'},
 {name:'Coastal 4',brand:'NRS',price:'$180',condition:'Good',category:'Paddle',location:'Riverview',image:'/assets/photography/fundy-paddle.jpg',alt:'Kayak on coastal water'},
 {name:'Trail 26',brand:'MEC',price:'$70',condition:'Very good',category:'Day packs',location:'Dieppe',image:'/assets/photography/fundy-coast.jpg',alt:'Bay of Fundy coastline'}
];
export default function Drop(){return <>
<section className="bg-forest text-white"><div className="container-x grid min-h-[620px] items-center gap-12 py-16 lg:grid-cols-[1fr_.85fr]"><div><span className="pill border-white/20 bg-white/10 text-sand">Every Tuesday · Fresh Drop</span><h1 className="display mt-6 text-6xl leading-[.88] sm:text-8xl">See it.<br/><span className="text-sand">Claim it.</span><br/>Get outside.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/65">Every Monday we photograph, grade and price the week's best consignments. Tuesday, we sell them live before the remaining gear lands online.</p><div className="mt-8 flex flex-wrap gap-3"><button className="btn-secondary"><Radio size={16}/> Watch the live drop</button><Link href="/shop" className="btn-ghost">Shop what's live <ArrowRight size={16}/></Link></div></div><div className="relative min-h-[420px] overflow-hidden rounded-[2.5rem] border border-sand/20"><Image src="/assets/photography/gear-tag.jpg" alt="Outdoor gear ready for a Tide & Trail drop" fill sizes="(max-width:1024px) 100vw, 40vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-forest/90 via-forest/15 to-transparent"/><div className="absolute bottom-7 left-7 right-7"><div className="text-xs font-black uppercase tracking-[.2em] text-sand">The weekly ritual</div><div className="display mt-2 text-4xl">Monday: prep.<br/>Tuesday: adventure.</div></div></div></div></section>
<section className="container-x py-20"><div className="grid gap-5 md:grid-cols-3"><Step icon={ShoppingBag} title="Consigned" text="People send us the gear they're finished with. We inspect it, price it and give it a second chance."/><Step icon={Clock} title="Monday" text="One focused processing day: clean, photograph, grade, write and schedule the drop."/><Step icon={Radio} title="Tuesday" text="The community gets first look in a live sale. Anything left becomes fresh inventory online."/></div></section>
<section className="bg-sand/35 py-20"><div className="container-x"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="pill">This week's drop</span><h2 className="display mt-4 text-5xl text-forest">Fresh gear. Fresh stories.</h2><p className="mt-3 max-w-2xl text-forest/60">No endless scrolling through stale inventory. New pieces arrive together, every Tuesday.</p></div><Link href="/sell" className="btn-primary">Put gear in next week's drop <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{drop.map((p,i)=><ProductCard key={p.name} p={p} i={i}/>)}</div></div></section></>}
function Step({icon:Icon,title,text}:{icon:any,title:string,text:string}){return <article className="rounded-3xl bg-white p-7 shadow-soft"><div className="grid h-11 w-11 place-items-center rounded-full bg-fog text-forest"><Icon size={20}/></div><h3 className="display mt-6 text-3xl text-forest">{title}</h3><p className="mt-3 text-sm leading-6 text-forest/60">{text}</p></article>}
