'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import Link from 'next/link'

type Adventure={id:string;created_at:string;name:string;email:string;title:string;adventure_type:string;location:string;starts_at:string|null;description:string;status:string}
const statuses=['pending','published','closed','declined']
const input='w-full rounded-xl border border-forest/10 bg-fog px-4 py-3'

export default function AdventureReview(){
  const[authed,setAuthed]=useState<boolean|null>(null),[password,setPassword]=useState(''),[items,setItems]=useState<Adventure[]>([]),[selectedId,setSelectedId]=useState(''),[filter,setFilter]=useState('pending'),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const load=useCallback(async()=>{const r=await fetch('/api/adventure-review');if(r.status===401){setAuthed(false);return}const j=await r.json();if(!r.ok){setError(j.error||'Could not load adventures.');return}setItems(j.adventures);setAuthed(true)},[])
  useEffect(()=>{void load()},[load])
  const selected=items.find(x=>x.id===selectedId)||null
  const shown=useMemo(()=>filter==='all'?items:items.filter(x=>x.status===filter),[items,filter])
  async function login(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/gear-room/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok){setError('Incorrect password.');return}setPassword('');await load()}
  async function update(patch:Record<string,unknown>){if(!selected)return;setError('');setNotice('');const r=await fetch('/api/adventure-review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,...patch})});const j=await r.json();if(!r.ok){setError(j.error||'Could not save.');return}setItems(old=>old.map(x=>x.id===selected.id?j.adventure:x));setNotice(patch.status==='published'?'Published to the Adventure Board.':'Saved.')}
  async function logout(){await fetch('/api/gear-room/login',{method:'DELETE'});setAuthed(false);setItems([])}
  if(authed===null)return <main className="container-x py-24">Loading Adventure Review…</main>
  if(!authed)return <main className="container-x min-h-[70vh] py-20"><form onSubmit={login} className="mx-auto max-w-md rounded-3xl bg-white p-8 shadow-soft"><span className="pill">Internal operations</span><h1 className="display mt-5 text-5xl text-forest">Adventure Review</h1><p className="mt-3 text-forest/60">Use your Gear Room password to review community posts.</p><label className="mt-7 block text-sm font-bold">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className={input+' mt-2'} required/></label>{error&&<p className="mt-3 text-sm font-bold text-red-700">{error}</p>}<button className="btn-primary mt-5 w-full">Sign in</button></form></main>
  return <main className="container-x py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="pill">Tide & Trail operations</span><h1 className="display mt-4 text-5xl text-forest">Adventure Review</h1><p className="mt-2 text-forest/60">Review community submissions before they reach the public board.</p></div><div className="flex gap-2"><Link href="/adventure-board" className="btn-ghost">View board</Link><button onClick={logout} className="btn-ghost">Sign out</button></div></div>
  {error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{notice&&<p className="mt-5 rounded-xl bg-sage p-3 text-sm font-bold text-forest">{notice}</p>}
  <div className="mt-8 flex gap-2 overflow-x-auto pb-2">{[...statuses,'all'].map(s=><button key={s} onClick={()=>setFilter(s)} className={'whitespace-nowrap rounded-full px-4 py-2 text-xs font-black '+(filter===s?'bg-forest text-white':'bg-white text-forest')}>{s.replace(/^./,c=>c.toUpperCase())} ({s==='all'?items.length:items.filter(i=>i.status===s).length})</button>)}</div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[360px_1fr]"><section className="grid content-start gap-3">{shown.map(a=><button key={a.id} onClick={()=>{setSelectedId(a.id);setNotice('')}} className={'rounded-2xl bg-white p-5 text-left ring-1 '+(selectedId===a.id?'ring-2 ring-rust':'ring-forest/10')}><span className="text-xs font-black uppercase tracking-wider text-rust">{a.adventure_type} · {a.status}</span><h2 className="mt-1 font-black text-forest">{a.title}</h2><p className="mt-1 text-sm text-forest/55">{a.name} · {new Date(a.created_at).toLocaleDateString('en-CA')}</p></button>)}{!shown.length&&<p className="rounded-2xl bg-white p-6 text-forest/50">No submissions here.</p>}</section>
  <section>{selected?<div className="rounded-3xl bg-white p-6 shadow-soft sm:p-8"><div className="flex flex-wrap justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-wider text-rust">Submitted by</span><h2 className="display mt-2 text-4xl text-forest">{selected.name}</h2><a href={'mailto:'+selected.email} className="text-sm underline">{selected.email}</a><p className="mt-1 text-xs text-forest/50">Contact information is private and never shown on the public board.</p></div><select value={selected.status} onChange={e=>void update({status:e.target.value})} className="h-fit rounded-xl bg-fog px-4 py-3 font-bold">{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
  <div className="mt-7 grid gap-4"><label className="text-sm font-bold">Title<input defaultValue={selected.title} onBlur={e=>e.target.value!==selected.title&&void update({title:e.target.value})} className={input+' mt-1'}/></label><label className="text-sm font-bold">Type<select value={selected.adventure_type} onChange={e=>void update({adventureType:e.target.value})} className={input+' mt-1'}>{['Hike','Paddle','Camp','Trail run','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-bold">Public general location<input defaultValue={selected.location} onBlur={e=>e.target.value!==selected.location&&void update({location:e.target.value})} className={input+' mt-1'}/></label><label className="text-sm font-bold">Date and time<input type="datetime-local" defaultValue={selected.starts_at?selected.starts_at.slice(0,16):''} onBlur={e=>void update({startsAt:e.target.value})} className={input+' mt-1'}/></label><label className="text-sm font-bold">Public description<textarea defaultValue={selected.description} onBlur={e=>e.target.value!==selected.description&&void update({description:e.target.value})} className={input+' mt-1 min-h-36'}/></label></div>
  <div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void update({status:'published'})} className="btn-primary">Approve & publish</button><button onClick={()=>void update({status:'declined'})} className="btn-ghost">Decline</button>{selected.status==='published'&&<button onClick={()=>void update({status:'closed'})} className="btn-ghost">Close adventure</button>}</div></div>:<div className="rounded-3xl bg-white p-10 text-center text-forest/55">Select a submission to review.</div>}</section></div></main>
}