import Link from 'next/link';
import {ArrowRight, Compass, HeartHandshake, Recycle, Wrench} from 'lucide-react';
import {HeroArt} from '@/components/HeroArt';
import {SectionTitle} from '@/components/SectionTitle';
import {AdventureCards} from '@/components/AdventureCards';
import {ProductCard,Product} from '@/components/ProductCard';

const products:Product[]=[
 {name:'Alpine 55 Pack',brand:'Osprey',price:'$165',condition:'Excellent',category:'Packs',location:'Moncton'},
 {name:'Hubba Hubba 2',brand:'MSR',price:'$310',condition:'Like new',category:'Camping',location:'Moncton'},
 {name:'Trail 26',brand:'MEC',price:'$70',condition:'Very good',category:'Day packs',location:'Dieppe'},
 {name:'Coastal 4',brand:'NRS',price:'$180',condition:'Good',category:'Paddle',location:'Riverview'}
];
export default function Home(){return <>
<section className="overflow-hidden bg-fog"><div className="container-x grid min-h-[650px] items-center gap-12 py-14 lg:grid-cols-[1.02fr_.98fr] lg:py-20"><div><span className="pill">Moncton · Bay of Fundy</span><h1 className="display mt-7 max-w-3xl text-6xl leading-[.9] text-forest sm:text-7xl lg:text-[88px]">Good gear.<br/><span className="text-rust">Another adventure.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-forest/65">Tide & Trail is an outdoor gear marketplace built around a simple idea: getting outside is better when you have the right gear — and someone to share it with.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="btn-primary">Find your next adventure <ArrowRight size={17}/></Link><Link href="/community" className="btn-ghost">Find your people</Link></div><div className="mt-10 flex flex-wrap gap-6 text-xs font-bold uppercase tracking-[.16em] text-forest/50"><span>Buy</span><span>Sell</span><span>Rent</span><span>Repair</span><span>Connect</span></div></div><HeroArt/></div></section>
<section className="border-y border-forest/10 bg-white"><div className="container-x grid gap-8 py-10 sm:grid-cols-3"><div><Recycle className="text-rust"/><h3 className="mt-3 font-black">Give good gear another life.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Curated consignment keeps quality equipment moving instead of gathering dust.</p></div><div><HeartHandshake className="text-rust"/><h3 className="mt-3 font-black">Find your people.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Hikes, paddles, coffee and community for people who want to get outside together.</p></div><div><Wrench className="text-rust"/><h3 className="mt-3 font-black">Don't replace it yet.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Our future repair studio will help you keep the gear you love going.</p></div></div></section>
<section className="container-x py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionTitle eyebrow="The community layer" title="The best part of the adventure might be who you meet." body="We're building the thing outdoor life has been missing: a local place to find a trail, a coffee, a paddle buddy, a campfire or simply someone to say hello to."/><Link href="/community" className="btn-ghost shrink-0">Explore community <ArrowRight size={16}/></Link></div><div className="mt-10"><AdventureCards/></div></section>
<section className="bg-sand/35 py-20"><div className="container-x"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><SectionTitle eyebrow="Just landed" title="Good gear, waiting for a second adventure." body="Every piece has a history. Every piece is inspected, priced honestly and ready to get back outside."/><Link href="/shop" className="btn-primary w-fit">Shop all gear <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((p,i)=><ProductCard key={p.name} p={p} i={i}/>)}</div></div></section>
<section className="container-x py-20"><div className="overflow-hidden rounded-[2.5rem] bg-forest"><div className="grid lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 text-white sm:p-12"><span className="pill border-white/20 bg-white/10 text-sand">Fundy Footpath</span><h2 className="display mt-6 text-5xl sm:text-6xl">Walk in.<br/>We’ll help you gear up.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/65">Passing through Moncton for the Fundy Footpath? Rent a lightweight kit for 3–5 days, pick it up here, and return it when your adventure is done.</p><Link href="/rent" className="btn-secondary mt-7">See Footpath rentals <ArrowRight size={16}/></Link></div><div className="relative min-h-[330px] bg-fundy topo"><div className="absolute inset-10 rounded-[2rem] border border-sand/30"/><div className="absolute bottom-10 left-10 text-sand"><Compass size={80} strokeWidth={1}/></div><div className="absolute right-10 top-10 max-w-[180px] text-right text-xs font-bold uppercase leading-5 tracking-[.18em] text-white/60">Moncton is your basecamp for the Bay of Fundy.</div></div></div></div></section>
<section className="bg-fog py-20"><div className="container-x text-center"><span className="pill">Hush Hush</span><h2 className="display mx-auto mt-5 max-w-3xl text-5xl text-forest sm:text-6xl">Sometimes the best plans are the ones you don't know yet.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-forest/60">Secret trailheads. Pop-up coffee. A small group of strangers who might not be strangers by the end of the morning.</p><Link href="/community" className="btn-primary mt-7">See the next secret adventure</Link></div></section>
</>}
