import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,HeartHandshake,Recycle,Wrench,Radio,Camera,Footprints} from 'lucide-react';
import {HeroArt} from '@/components/HeroArt';
import {SectionTitle} from '@/components/SectionTitle';
import {AdventureCards} from '@/components/AdventureCards';
import {ProductCard,Product} from '@/components/ProductCard';

const products:Product[]=[
 {name:'Trail Pack 55',brand:'Osprey',price:'$165',condition:'Excellent',category:'Packs',location:'Moncton',image:'/assets/photography/fundy-hiker.jpg',alt:'Hiker wearing a technical backpack'},
 {name:'Hubba Hubba 2',brand:'MSR',price:'$310',condition:'Like new',category:'Camping',location:'Moncton',image:'/assets/photography/fundy-forest.jpg',alt:'Forest trail beside lush greenery'},
 {name:'Trail 26',brand:'MEC',price:'$70',condition:'Very good',category:'Day packs',location:'Dieppe',image:'/assets/photography/fundy-coast.jpg',alt:'Coastal view over the Bay of Fundy'},
 {name:'Coastal 4',brand:'NRS',price:'$180',condition:'Good',category:'Paddle',location:'Riverview',image:'/assets/photography/fundy-paddle.jpg',alt:'Kayak on calm coastal water'}
];
export default function Home(){return <>
<section className="overflow-hidden bg-fog"><div className="container-x grid min-h-[650px] items-center gap-12 py-14 lg:grid-cols-[1.02fr_.98fr] lg:py-20"><div><span className="pill">Moncton · Bay of Fundy</span><h1 className="display mt-7 max-w-3xl text-6xl leading-[.9] text-forest sm:text-7xl lg:text-[88px]">Good gear.<br/><span className="text-rust">Another adventure.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-forest/65">Tide & Trail is an outdoor gear marketplace built around a simple idea: getting outside is better when you have the right gear — and someone to share it with.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/shop" className="btn-primary">Find your next adventure <ArrowRight size={17}/></Link><Link href="/community" className="btn-ghost">Find your people</Link></div><div className="mt-10 flex flex-wrap gap-6 text-xs font-bold uppercase tracking-[.16em] text-forest/50"><span>Buy</span><span>Sell</span><span>Rent</span><span>Repair</span><span>Connect</span></div></div><HeroArt/></div></section>
<section className="border-y border-forest/10 bg-white"><div className="container-x grid gap-8 py-10 sm:grid-cols-3"><div><Recycle className="text-rust"/><h3 className="mt-3 font-black">Give good gear another life.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Curated consignment keeps quality equipment moving instead of gathering dust.</p></div><div><HeartHandshake className="text-rust"/><h3 className="mt-3 font-black">Find your people.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Hikes, paddles, coffee and community for people who want to get outside together.</p></div><div><Wrench className="text-rust"/><h3 className="mt-3 font-black">Don't replace it yet.</h3><p className="mt-2 text-sm leading-6 text-forest/60">Our future repair studio will help you keep the gear you love going.</p></div></div></section>
<section className="container-x py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionTitle eyebrow="The community layer" title="The best part of the adventure might be who you meet." body="We're building the thing outdoor life has been missing: a local place to find a trail, a coffee, a paddle buddy, a campfire or simply someone to say hello to."/><Link href="/community" className="btn-ghost shrink-0">Explore community <ArrowRight size={16}/></Link></div><div className="mt-10"><AdventureCards/></div></section>
<section className="bg-forest py-20 text-white"><div className="container-x grid gap-10 lg:grid-cols-[1fr_1.15fr] lg:items-center"><div><span className="pill border-white/20 bg-white/10 text-sand">Fresh Drop Tuesday</span><h2 className="display mt-5 text-5xl sm:text-6xl">The week's best gear gets its first shot live.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/65">Monday is photography and listing day. Tuesday is the drop. Watch on Facebook or Whatnot, grab something before it reaches the site, then shop whatever remains online.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/drop" className="btn-secondary"><Radio size={16}/> See the next drop</Link><Link href="/sell" className="btn-ghost">Put gear in the next one</Link></div></div><div className="relative overflow-hidden rounded-[2rem]"><Image src="/assets/photography/gear-tag.jpg" alt="Gear prepared for a Tide & Trail drop" width={1200} height={800} className="h-auto w-full"/><div className="absolute inset-0 bg-gradient-to-t from-forest/75 to-transparent"/><div className="absolute bottom-6 left-6 text-white"><div className="text-xs font-black uppercase tracking-[.18em] text-sand">One day. One drop. New stories.</div></div></div></div></section>
<section className="bg-sand/35 py-20"><div className="container-x"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-end"><SectionTitle eyebrow="Just landed" title="Good gear, waiting for a second adventure." body="Every piece has a history. Every piece is inspected, priced honestly and ready to get back outside."/><Link href="/shop" className="btn-primary w-fit">Shop all gear <ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map((p,i)=><ProductCard key={p.name} p={p} i={i}/>)}</div></div></section>
<section className="container-x py-20"><div className="overflow-hidden rounded-[2.5rem] bg-forest"><div className="grid lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 text-white sm:p-12"><span className="pill border-white/20 bg-white/10 text-sand">Fundy Footpath</span><h2 className="display mt-6 text-5xl sm:text-6xl">Walk in.<br/>We'll help you gear up.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/65">Passing through Moncton for the Fundy Footpath? Rent a lightweight kit for 3–5 days, pick it up here, and return it when your adventure is done.</p><Link href="/rent" className="btn-secondary mt-7">See Footpath rentals <ArrowRight size={16}/></Link></div><div className="relative min-h-[330px] overflow-hidden bg-fundy"><Image src="/assets/photography/fundy-hiker.jpg" alt="Hiker overlooking the Bay of Fundy" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-forest/80 to-transparent"/><div className="absolute right-8 top-8 max-w-[180px] text-right text-xs font-bold uppercase leading-5 tracking-[.18em] text-white/80">Moncton is your basecamp for the Bay of Fundy.</div></div></div></div></section>
<section className="bg-fog py-20"><div className="container-x grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><span className="pill">Nomads Cafe · Nomad's Cafe · $5</span><h2 className="display mt-5 max-w-3xl text-5xl text-forest sm:text-6xl">Sometimes the best plans are the ones you don't know yet.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-forest/60">Secret trailheads. Pop-up coffee. A small group of strangers who might not be strangers by the end of the morning.</p><a href="https://square.link/u/1eDmFUid" className="btn-primary mt-7">Buy Tickets</a></div><div className="relative overflow-hidden rounded-[2rem] shadow-soft"><Image src="/images/nathan-dumlao-ozVQrfENFOs-unsplash.jpg" alt="Hush Hush coffee event at Nomad's Cafe" width={1280} height={800} className="h-auto w-full" /></div></div></section>
<section className="container-x py-20"><div className="grid gap-5 md:grid-cols-3"><div className="card p-7"><Camera className="text-rust"/><h3 className="display mt-5 text-3xl text-forest">Send a picture.</h3><p className="mt-3 text-sm leading-6 text-forest/60">We give you a recommended selling price before you haul anything anywhere.</p><Link href="/sell" className="mt-6 inline-flex font-bold text-forest">Sell your gear <ArrowRight size={16}/></Link></div><div className="card p-7"><Footprints className="text-rust"/><h3 className="display mt-5 text-3xl text-forest">Rent for the big trip.</h3><p className="mt-3 text-sm leading-6 text-forest/60">Especially useful for visitors passing through for 3–5 days on the Footpath.</p><Link href="/rent" className="mt-6 inline-flex font-bold text-forest">Build a kit <ArrowRight size={16}/></Link></div><div className="card p-7"><HeartHandshake className="text-rust"/><h3 className="display mt-5 text-3xl text-forest">Come for the people.</h3><p className="mt-3 text-sm leading-6 text-forest/60">The missing layer: events, trail knowledge and people who actually want to make plans.</p><Link href="/community" className="mt-6 inline-flex font-bold text-forest">Join the community <ArrowRight size={16}/></Link></div></div></section>
</>}
