'use client';
import {CalendarDays, MapPin, Plus, Users} from 'lucide-react';
import {useState} from 'react';
const posts=[
 {type:'LOOKING FOR COMPANY',title:'Fundy Footpath · Sept 18–21',body:'Moderate pace, happy to split shuttle costs. I have room for one more in the car.',meta:'2 people interested',place:'Fundy Coast'},
 {type:'HIKE',title:'Kouchibouguac Saturday',body:'Easy 8–10 km loop. Coffee after. New to the area? Come along.',meta:'5 going',place:'Kouchibouguac'},
 {type:'PADDLE',title:'Anyone up for a sunset paddle?',body:'Planning a calm-water paddle this Thursday around 6. Bring your own PFD.',meta:'3 interested',place:'Shediac area'}
];
export function CommunityBoard(){const [open,setOpen]=useState(false);return <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{posts.map((p,i)=><article key={i} className="rounded-3xl border border-forest/10 bg-white p-5"><div className="flex flex-wrap items-center gap-2"><span className="pill">{p.type}</span><span className="text-xs text-forest/50">{p.place}</span></div><h3 className="mt-4 text-xl font-black text-forest">{p.title}</h3><p className="mt-2 text-sm leading-6 text-forest/65">{p.body}</p><div className="mt-4 flex items-center gap-4 text-xs font-bold text-forest/55"><span className="flex items-center gap-1"><Users size={14}/>{p.meta}</span><span className="flex items-center gap-1"><MapPin size={14}/>{p.place}</span></div></article>)}</div><aside className="rounded-3xl bg-forest p-6 text-white"><div className="grid h-11 w-11 place-items-center rounded-full bg-sand text-forest"><Plus/></div><h3 className="display mt-8 text-3xl">Put an adventure on the board.</h3><p className="mt-3 text-sm leading-6 text-white/65">Have a spare seat, need a hiking partner, or just want to invite people outside? Post it.</p><button onClick={()=>setOpen(true)} className="btn-secondary mt-6 w-full">Share an adventure</button>{open&&<div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm">Thanks! In the full app this opens the posting flow. For now, email <a className="font-bold text-sand" href="mailto:hello@tideandtrail.ca">hello@tideandtrail.ca</a>.</div>}</aside></div>}
