'use client'
import { useState } from 'react'
export default function SignupForm({ type, eventId, eventTitle }: { type: 'newsletter'|'membership'|'event'; eventId?: string; eventTitle?: string }) {
 const [done,setDone]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);let body:any={name:f.get('name'),email:f.get('email'),phone:f.get('phone'),marketingOptIn:f.get('marketing')==='on'};let url=''
 if(type==='newsletter'){body={email:f.get('email'),firstName:f.get('name'),source:'website'};url='/api/newsletter'}
 if(type==='membership'){body={...body,tier:f.get('tier')};url='/api/membership'}
 if(type==='event'){body={...body,eventId,guests:Number(f.get('guests')||1),notes:f.get('notes')};url='/api/events/signup'}
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setLoading(false);if(!r.ok){setError(j.error||'Something went wrong.');return}setDone(true)}
 if(done)return <div className="rounded-3xl bg-[#DCEBE6] p-8"><div className="text-xs font-black uppercase tracking-widest text-[#C96D3A]">You're in</div><h3 className="mt-2 text-3xl font-black text-[#163C38]">Adventure incoming.</h3><p className="mt-3 text-black/60">{type==='newsletter'?'Watch your inbox for Fresh Drop Tuesday and upcoming adventures.':type==='membership'?'Welcome to the Tide & Trail community.':'Your spot is reserved. We’ll send the details by email.'}</p></div>
 return <form onSubmit={submit} className="grid gap-4">{type!=='newsletter'&&<input name="name" required placeholder="Your name" className="rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"/>}<input name="email" required type="email" placeholder="you@example.com" className="rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"/>{type==='event'&&<><input name="phone" placeholder="Phone (optional)" className="rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"/><select name="guests" className="rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"><option value="1">1 person</option><option value="2">2 people</option><option value="3">3 people</option><option value="4">4 people</option></select><textarea name="notes" placeholder="Anything we should know?" className="min-h-28 rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"/></>}{type==='membership'&&<select name="tier" className="rounded-2xl border border-black/10 bg-[#F4F0E6] px-4 py-3.5"><option value="community">Community — free</option><option value="trail">Trail Member — $5/month</option><option value="founding">Founding Member — $10/month</option></select>}<label className="flex gap-2 text-sm text-black/60"><input name="marketing" type="checkbox" defaultChecked/> Send me Tide & Trail news, drops and events.</label>{error&&<p className="text-sm font-bold text-red-700">{error}</p>}<button disabled={loading} className="rounded-full bg-[#163C38] px-6 py-3 font-bold text-white disabled:opacity-50">{loading?'Saving…':type==='event'?`Join ${eventTitle||'event'} →`:type==='membership'?'Join Tide & Trail →':'Get the good stuff →'}</button></form>
}
