'use client';
import {Search, SlidersHorizontal} from 'lucide-react';
import {useMemo,useState} from 'react';
import {ProductCard,Product} from '@/components/ProductCard';
const products:Product[]=[
{name:'Trail Pack 55',brand:'Osprey',price:'$165',condition:'Excellent',category:'Packs',location:'Moncton',image:'/assets/photography/fundy-hiker.jpg',alt:'Hiker wearing a technical backpack'},
{name:'Hubba Hubba 2',brand:'MSR',price:'$310',condition:'Like new',category:'Camping',location:'Moncton',image:'/assets/photography/fundy-forest.jpg',alt:'Forest trail in Atlantic Canada'},
{name:'Trail 26',brand:'MEC',price:'$70',condition:'Very good',category:'Day packs',location:'Dieppe',image:'/assets/photography/fundy-coast.jpg',alt:'Bay of Fundy coastline'},
{name:'Coastal 4',brand:'NRS',price:'$180',condition:'Good',category:'Paddle',location:'Riverview',image:'/assets/photography/fundy-paddle.jpg',alt:'Kayak on coastal water'},
{name:'Quest 2 Tent',brand:'Big Agnes',price:'$245',condition:'Excellent',category:'Camping',location:'Moncton',image:'/assets/photography/fundy-forest.jpg',alt:'Forest campsite setting'},
{name:'X Ultra 4',brand:'Salomon',price:'$95',condition:'Good',category:'Footwear',location:'Dieppe',image:'/assets/photography/fundy-hiker.jpg',alt:'Hiker on a coastal adventure'},
{name:'Trail Stove',brand:'MSR',price:'$45',condition:'Very good',category:'Camp kitchen',location:'Moncton',image:'/assets/photography/mug.jpg',alt:'Outdoor camp mug'},
{name:'Coastline 28',brand:'Patagonia',price:'$120',condition:'Excellent',category:'Packs',location:'Riverview',image:'/assets/photography/fundy-coast.jpg',alt:'Coastal Bay of Fundy landscape'}];
export default function Shop(){const [q,setQ]=useState('');const [cat,setCat]=useState('All');const cats=['All','Camping','Packs','Paddle','Footwear','Camp kitchen'];const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&(`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q.toLowerCase()))),[q,cat]);return <section className="container-x py-16"><div className="max-w-3xl"><span className="pill">The marketplace</span><h1 className="display mt-5 text-6xl text-forest sm:text-7xl">Find gear with a history.</h1><p className="mt-5 text-lg leading-8 text-forest/60">Curated, pre-loved outdoor gear from people around Moncton and the Bay of Fundy.</p></div><div className="mt-10 flex flex-col gap-4 rounded-3xl border border-forest/10 bg-white p-4 md:flex-row"><div className="flex flex-1 items-center gap-3 rounded-2xl bg-fog px-4"><Search size={18} className="text-forest/50"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search packs, tents, kayaks..." className="w-full bg-transparent py-3 text-sm outline-none"/></div><div className="flex items-center gap-2 overflow-auto"><SlidersHorizontal size={16} className="ml-2 text-forest/50"/>{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${cat===c?'bg-forest text-white':'bg-fog text-forest/65'}`}>{c}</button>)}</div></div><div className="mt-8 flex items-center justify-between text-xs font-bold uppercase tracking-[.15em] text-forest/50"><span>{filtered.length} pieces ready for an adventure</span><span>Local pickup · Moncton</span></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((p,i)=><ProductCard key={p.name} p={p} i={i}/>)}</div></section>}
