'use client'
import Image from 'next/image'
import { useCallback, useEffect, useMemo, useState } from 'react'

type Submission = { id:string; created_at:string; name:string; email:string; phone?:string; item_name:string; brand?:string; category?:string; condition?:string; adventure_story?:string; description?:string; estimated_purchase_price?:number; preferred_payout?:string; pickup_postal_code?:string; status:string; staff_notes?:string; list_price?:number; photo_urls?:string[] }
const statuses = ['new','reviewing','accepted','drop_off','photography','graded','priced','ready_for_tuesday','live','sold','paid','declined']
const conditions = ['Pristine','Excellent','Good','Worn & Ready','Repair / Project']
const messages = [['received','Submission received'],['more_photos','Request more photos'],['accepted','Item accepted'],['drop_off','Arrange drop-off'],['declined','Item declined'],['listed','Item listed'],['sold','Item sold'],['payout_ready','Payout ready']]
const label = (value:string) => value.replaceAll('_',' ').replace(/\b\w/g, x => x.toUpperCase())

export default function GearRoom() {
  const [authed,setAuthed]=useState<boolean|null>(null), [password,setPassword]=useState(''), [items,setItems]=useState<Submission[]>([]), [selectedId,setSelectedId]=useState(''), [filter,setFilter]=useState('new'), [error,setError]=useState(''), [notice,setNotice]=useState('')
  const load=useCallback(async()=>{const r=await fetch('/api/gear-room/submissions');if(r.status===401){setAuthed(false);return}const j=await r.json();if(!r.ok){setError(j.error||'Could not load submissions.');setAuthed(false);return}setItems(j.submissions);setAuthed(true)},[])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  const selected=items.find(x=>x.id===selectedId)||null
  const shown=useMemo(()=>filter==='all'?items:items.filter(x=>x.status===filter),[items,filter])
  async function login(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/gear-room/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok){setError('Incorrect password.');return}setPassword('');await load()}
  async function update(patch:Record<string,unknown>){if(!selected)return;setError('');const r=await fetch('/api/gear-room/submissions',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,...patch})});const j=await r.json();if(!r.ok){setError(j.error||'Could not save.');return}setItems(old=>old.map(x=>x.id===selected.id?{...x,...j.submission}:x));setNotice('Saved.')}
  async function queue(type:string){if(!selected)return;const r=await fetch('/api/gear-room/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submissionId:selected.id,type})});const j=await r.json();if(!r.ok){setError(j.error||'Could not queue message.');return}await navigator.clipboard?.writeText(`${j.message.subject}\n\n${j.message.body}`);setNotice('Message queued and copied to your clipboard.')}
  async function logout(){await fetch('/api/gear-room/login',{method:'DELETE'});setAuthed(false);setItems([])}
  if(authed===null)return <main className="container-x py-24">Loading Gear Room…</main>
  if(!authed)return <main className="container-x min-h-[70vh] py-20"><form onSubmit={login} className="mx-auto max-w-md rounded-3xl bg-white p-8 shadow-soft"><span className="pill">Internal operations</span><h1 className="display mt-5 text-5xl text-forest">Gear Room</h1><p className="mt-3 text-forest/60">Sign in to manage the consignment workflow.</p><label className="mt-7 block text-sm font-bold">Password<input aria-label="Gear Room password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-2xl border border-forest/15 bg-fog px-4 py-3" required/></label>{error&&<p role="alert" className="mt-3 text-sm font-bold text-red-700">{error}</p>}<button className="btn-primary mt-5 w-full">Enter Gear Room</button></form></main>
  return <main className="container-x py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="pill">Tide & Trail operations</span><h1 className="display mt-4 text-5xl text-forest">Gear Room</h1><p className="mt-2 text-forest/60">Review, prepare, list, sell, and pay out.</p></div><button onClick={logout} className="btn-ghost">Sign out</button></div>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}{notice&&<p role="status" className="mt-5 rounded-xl bg-sage p-3 text-sm font-bold text-forest">{notice}</p>}
  <div className="mt-8 flex gap-2 overflow-x-auto pb-2">{['new',...statuses.slice(1),'all'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-black ${filter===x?'bg-forest text-white':'bg-white text-forest'}`}>{label(x)} ({x==='all'?items.length:items.filter(i=>i.status===x).length})</button>)}</div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[360px_1fr]"><section className="grid content-start gap-3">{shown.map(item=><button key={item.id} onClick={()=>{setSelectedId(item.id);setNotice('')}} className={`rounded-2xl bg-white p-5 text-left ring-1 ${selectedId===item.id?'ring-2 ring-rust':'ring-forest/10'}`}><span className="text-xs font-black uppercase tracking-wider text-rust">{label(item.status)}</span><h2 className="mt-1 font-black text-forest">{item.item_name}</h2><p className="mt-1 text-sm text-forest/55">{item.name} · {new Date(item.created_at).toLocaleDateString('en-CA')}</p></button>)}{!shown.length&&<p className="rounded-2xl bg-white p-6 text-forest/50">No submissions here.</p>}</section>
  <section>{selected?<div className="rounded-3xl bg-white p-6 shadow-soft sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:justify-between"><div><span className="text-xs font-black uppercase tracking-wider text-rust">{selected.category||'Outdoor gear'}</span><h2 className="display mt-2 text-4xl text-forest">{selected.item_name}</h2><p className="text-forest/60">{selected.brand||'Brand not supplied'} · {selected.name}</p></div><label className="text-sm font-bold">Workflow status<select value={selected.status} onChange={e=>void update({status:e.target.value})} className="mt-2 block rounded-xl bg-fog px-4 py-3">{statuses.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label></div>
  {!!selected.photo_urls?.length&&<div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{selected.photo_urls.map((url,i)=><div key={url} className="relative aspect-square overflow-hidden rounded-2xl bg-fog"><Image src={url} alt={`${selected.item_name} photo ${i+1}`} fill unoptimized className="object-cover"/></div>)}</div>}
  <div className="mt-7 grid gap-5 sm:grid-cols-2"><div className="rounded-2xl bg-fog p-5"><h3 className="text-xs font-black uppercase tracking-wider text-rust">Consignor</h3><p className="mt-2 font-bold">{selected.name}</p><a className="block text-sm underline" href={`mailto:${selected.email}`}>{selected.email}</a><p className="text-sm">{selected.phone||'No phone'} · {selected.pickup_postal_code||'No postal code'}</p></div><div className="rounded-2xl bg-fog p-5"><h3 className="text-xs font-black uppercase tracking-wider text-rust">Payout and pricing</h3><p className="mt-2 text-sm">{selected.preferred_payout==='credit'?'Store credit — 70%':'Cash — 60%'}</p><p className="text-sm">Original price: {selected.estimated_purchase_price?`$${selected.estimated_purchase_price}`:'Not supplied'}</p><label className="mt-3 block text-sm font-bold">Listing price<input type="number" min="0" defaultValue={selected.list_price||''} onBlur={e=>e.target.value&&void update({listPrice:e.target.value})} className="mt-1 w-full rounded-xl border border-forest/10 bg-white px-3 py-2"/></label></div></div>
  <label className="mt-5 block text-sm font-bold">Condition<select value={selected.condition||''} onChange={e=>void update({condition:e.target.value})} className="mt-2 w-full rounded-xl bg-fog px-4 py-3"><option value="" disabled>Select a grade</option>{conditions.map(x=><option key={x}>{x}</option>)}</select></label><div className="mt-5 rounded-2xl bg-sage p-5"><h3 className="text-xs font-black uppercase tracking-wider text-rust">Adventure story</h3><p className="mt-2 whitespace-pre-wrap">{selected.adventure_story||'No story supplied.'}</p></div><div className="mt-5"><h3 className="text-xs font-black uppercase tracking-wider text-rust">Description</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-forest/70">{selected.description||'No description supplied.'}</p></div><label className="mt-5 block text-sm font-bold">Staff notes<textarea defaultValue={selected.staff_notes||''} onBlur={e=>void update({staffNotes:e.target.value})} className="mt-2 min-h-28 w-full rounded-2xl bg-fog px-4 py-3"/></label><div className="mt-6"><h3 className="text-xs font-black uppercase tracking-wider text-rust">Consignor communication</h3><div className="mt-3 flex flex-wrap gap-2">{messages.map(([type,text])=><button key={type} onClick={()=>void queue(type)} className="btn-ghost">{text}</button>)}</div></div></div>:<div className="rounded-3xl bg-white p-10 text-center text-forest/55">Select a submission to begin.</div>}</section></div></main>
}
